BIN_DIR = /usr/bin
LIB_DIR = /usr/lib/uml

all : 

install :
	install -d $(DESTDIR)$(BIN_DIR)
	install mkrootfs $(DESTDIR)$(BIN_DIR)
	install -d $(DESTDIR)$(LIB_DIR)
	install functions $(DESTDIR)$(LIB_DIR)

clean :
